apiVersion: v1
kind: Pod
metadata:
  name: sklearn-ml-api
spec:
  containers:
    - image: ecoden/sklearn-ml-api:latest
      name: sklearn
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      command:
        ["sh", "-c", 'echo "Creating sklearn-ml-api pod ..." && sleep 3600']
      ports:
        - containerPort: 80
  restartPolicy: Always
