apiVersion: v1
kind: Pod
metadata:
  name: udacity-machine-learning-microservice
spec:
  containers:
    - image: gapspade/udacity-machine-learning-microservice
      name: machine-learning-ms
      imagePullPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      command:
        ["sh", "-c", 'echo "Creating udacity-machine-learning-microservice ..." && sleep 3600']
      ports:
        - containerPort: 80
  restartPolicy: Always
